name: Feature Request
description: Request a new feature.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to see added?
      description: Let me know here!
    validations:
      required: true
