name: Feature Request
description: Request a new feature.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Please explain in detail what you'd like to see added.
    validations:
      required: true
